name = "DifferentiablePiecewiseFunctions"
uuid = "c4074edc-5735-4946-9f30-5e6aab3fa22e"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
ChainRulesCore = "1"
ForwardDiff = "0.10"
julia = "1.9"
